/* ============================== DATA ==================================== */
const WORLD_W = 3000,
  WORLD_H = 3000;

const RESOURCE_TYPES = {
  bioResin: { name: 'Bio Resin', color: '#5dff7a', glow: 'rgba(93,255,122,', weight: 1, price: 12 },
  sporeFiber: {
    name: 'Spore Fiber',
    color: '#b06bff',
    glow: 'rgba(176,107,255,',
    weight: 2,
    price: 20,
  },
  salvageChips: {
    name: 'Salvage Chips',
    color: '#d8dde6',
    glow: 'rgba(216,221,230,',
    weight: 1,
    price: 10,
  },
  softQuartz: {
    name: 'Soft Quartz',
    color: '#6bd1ff',
    glow: 'rgba(107,209,255,',
    weight: 3,
    price: 28,
  },
  hiveEnzymes: {
    name: 'Hive Enzymes',
    color: '#ff5d8a',
    glow: 'rgba(255,93,138,',
    weight: 2,
    price: 65,
  },
};

const WEAPONS = {
  pulse: {
    key: 'pulse',
    name: 'Pulse Rifle',
    slot: 1,
    damage: 12,
    fireRate: 8,
    magSize: 36,
    reloadTime: 1.5,
    projSpeed: 760,
    projRadius: 3,
    spread: 0.04,
    pellets: 1,
    color: '#4df0ff',
    useHeat: false,
  },
  shotgun: {
    key: 'shotgun',
    name: 'Shotgun',
    slot: 2,
    damage: 8,
    fireRate: 1.1,
    magSize: 6,
    reloadTime: 1.8,
    projSpeed: 640,
    projRadius: 3,
    spread: 0.34,
    pellets: 7,
    color: '#ffb04d',
    useHeat: false,
  },
  arc: {
    key: 'arc',
    name: 'Arc Projector',
    slot: 3,
    damage: 7,
    tickRate: 10,
    range: 180,
    chain: 3,
    chainRange: 120,
    heatPerSec: 32,
    coolPerSec: 42,
    overheatLock: 30,
    color: '#6e8bff',
    useHeat: true,
  },
};

const ENEMY_TYPES = {
  skitterling: {
    name: 'Skitterling',
    hp: 35,
    speed: 120,
    damage: 8,
    attackCd: 0.8,
    radius: 11,
    range: 22,
    color: '#ff5d4d',
    score: 4,
    kind: 'melee',
  },
  sporeMantis: {
    name: 'Spore Mantis',
    hp: 90,
    speed: 75,
    damage: 14,
    attackCd: 1.5,
    radius: 14,
    range: 260,
    color: '#c06bff',
    score: 9,
    kind: 'ranged',
  },
  carapaceBull: {
    name: 'Carapace Bull',
    hp: 280,
    speed: 65,
    damage: 28,
    attackCd: 1.4,
    radius: 22,
    range: 30,
    color: '#ff9a3d',
    score: 18,
    kind: 'charger',
    armor: 0.35,
  },
  broodWarden: {
    name: 'Brood Warden',
    hp: 380,
    speed: 50,
    damage: 18,
    attackCd: 1.2,
    radius: 25,
    range: 34,
    color: '#b02040',
    score: 28,
    kind: 'warden',
  },
};

const UPGRADES = {
  cloneHealth: {
    name: 'Reinforced Clone Tissue',
    desc: '+20 max clone health',
    credits: 120,
    res: { bioResin: 10 },
    max: 5,
  },
  rifleDamage: {
    name: 'Rifle Capacitor',
    desc: '+15% Pulse Rifle damage',
    credits: 150,
    res: { softQuartz: 8 },
    max: 5,
  },
  cargoHarness: {
    name: 'Cargo Harness',
    desc: '+2 carry weight',
    credits: 100,
    res: { salvageChips: 10 },
    max: 5,
  },
  muleArmor: {
    name: 'Mule Armor',
    desc: '+100 HP for the Mule-3 hauler',
    credits: 160,
    res: { salvageChips: 15 },
    max: 5,
  },
  deviceCooling: {
    name: 'Device Cooling',
    desc: '-15% device cooldown',
    credits: 140,
    res: { sporeFiber: 8 },
    max: 4,
  },
  marketContacts: {
    name: 'Market Contacts',
    desc: '+10% resource sell price',
    credits: 200,
    res: {},
    max: 4,
  },
  signalArray: {
    name: 'Signal Array',
    desc: 'Signal Stability drops 25% slower',
    credits: 130,
    res: { softQuartz: 6 },
    max: 3,
  },
  hydroponicsTray: {
    name: 'Hydroponics Tray',
    desc: '+3 Bio Resin after each mission',
    credits: 180,
    res: { bioResin: 12 },
    max: 3,
  },
};

const MISSIONS = {
  resourceRun: {
    key: 'resourceRun',
    name: 'Resource Run',
    brief: 'Deliver 120 cr of resources to the Cargo Pad.',
    bonusBrief: 'Bonus: deliver 200+ cr.',
  },
  hivePurge: {
    key: 'hivePurge',
    name: 'Hive Purge',
    brief: 'Destroy 2 hives.',
    bonusBrief: 'Bonus: destroy a level 3 hive.',
  },
  outpostRecovery: {
    key: 'outpostRecovery',
    name: 'Outpost Recovery',
    brief: 'Activate the reactor, deliver 60 cr and hold for 90s.',
    bonusBrief: 'Bonus: Mule-3 must survive.',
  },
};

export { WORLD_W, WORLD_H, RESOURCE_TYPES, WEAPONS, ENEMY_TYPES, UPGRADES, MISSIONS };
