/* ============================== DATA ==================================== */
const WORLD_W = 3000,
  WORLD_H = 3000;

const RESOURCE_TYPES = {
  bioResin: { name: 'Bio Resin', color: '#5dff7a', glow: 'rgba(93,255,122,', weight: 1, price: 12 },
  sporeFiber: {
    name: 'Spore Fiber',
    color: '#b06bff',
    glow: 'rgba(176,107,255,',
    weight: 2,
    price: 20,
  },
  salvageChips: {
    name: 'Salvage Chips',
    color: '#d8dde6',
    glow: 'rgba(216,221,230,',
    weight: 1,
    price: 10,
  },
  softQuartz: {
    name: 'Soft Quartz',
    color: '#6bd1ff',
    glow: 'rgba(107,209,255,',
    weight: 3,
    price: 28,
  },
  hiveEnzymes: {
    name: 'Hive Enzymes',
    color: '#ff5d8a',
    glow: 'rgba(255,93,138,',
    weight: 2,
    price: 65,
  },
};

const WEAPONS = {
  pulse: {
    key: 'pulse',
    name: 'Pulse Rifle',
    slot: 1,
    damage: 12,
    fireRate: 8,
    magSize: 36,
    reloadTime: 1.5,
    projSpeed: 760,
    projRadius: 3,
    spread: 0.04,
    pellets: 1,
    color: '#4df0ff',
    useHeat: false,
  },
  shotgun: {
    key: 'shotgun',
    name: 'Shotgun',
    slot: 2,
    damage: 8,
    fireRate: 1.1,
    magSize: 6,
    reloadTime: 1.8,
    projSpeed: 640,
    projRadius: 3,
    spread: 0.34,
    pellets: 7,
    color: '#ffb04d',
    useHeat: false,
    range: 320,
  },
  arc: {
    key: 'arc',
    name: 'Arc Projector',
    slot: 3,
    damage: 7,
    tickRate: 10,
    range: 180,
    chain: 3,
    chainRange: 120,
    heatPerSec: 32,
    coolPerSec: 42,
    overheatLock: 30,
    color: '#6e8bff',
    useHeat: true,
  },
  railgun: {
    key: 'railgun',
    name: 'Railgun',
    slot: 4,
    damage: 60,
    fireRate: 1.1,
    magSize: 4,
    reloadTime: 2.2,
    projSpeed: 1500,
    projRadius: 4,
    spread: 0.005,
    pellets: 1,
    color: '#d07aff',
    useHeat: false,
    pierce: true,
    range: 900,
  },
  flak: {
    key: 'flak',
    name: 'Flak Launcher',
    slot: 5,
    damage: 26,
    fireRate: 1.5,
    magSize: 5,
    reloadTime: 2.0,
    projSpeed: 430,
    projRadius: 5,
    spread: 0.06,
    pellets: 1,
    color: '#ffb04d',
    useHeat: false,
    aoe: 90,
    status: 'burn',
    range: 460,
  },
  homingLauncher: {
    key: 'homingLauncher',
    name: 'Seeker Pods',
    slot: 6,
    damage: 14,
    fireRate: 2.2,
    magSize: 12,
    reloadTime: 2.0,
    projSpeed: 340,
    projRadius: 4,
    spread: 0.25,
    pellets: 1,
    color: '#5dff7a',
    useHeat: false,
    homing: true,
    aoe: 50,
    range: 1400,
  },
  ricochet: {
    key: 'ricochet',
    name: 'Ricochet SMG',
    slot: 7,
    damage: 10,
    fireRate: 7,
    magSize: 40,
    reloadTime: 1.6,
    projSpeed: 820,
    projRadius: 3,
    spread: 0.05,
    pellets: 1,
    color: '#8ab4ff',
    useHeat: false,
    bounce: 3,
    range: 1000,
  },
  cryoMortar: {
    key: 'cryoMortar',
    name: 'Cryo Mortar',
    slot: 8,
    damage: 20,
    fireRate: 1.0,
    magSize: 5,
    reloadTime: 2.2,
    projSpeed: 430,
    projRadius: 5,
    spread: 0.03,
    pellets: 1,
    color: '#9adfff',
    useHeat: false,
    lob: true,
    aoe: 100,
    status: 'freeze',
    range: 520,
  },
  chargeBeam: {
    key: 'chargeBeam',
    name: 'Charge Beam',
    slot: 9,
    damage: 18,
    fireRate: 2.5,
    magSize: 1,
    reloadTime: 0,
    projSpeed: 1100,
    projRadius: 4,
    spread: 0.01,
    pellets: 1,
    color: '#ffd35d',
    useHeat: true,
    heatPerSec: 26,
    coolPerSec: 38,
    overheatLock: 30,
    charge: true,
    pierce: true,
    range: 800,
  },
};

const DEVICES = {
  turret: { key: 'turret', name: 'Turret', cd: 25 },
  shield: { key: 'shield', name: 'Shield', cd: 18 },
  scanner: { key: 'scanner', name: 'Scan', cd: 12 },
  mine: { key: 'mine', name: 'Mine', cd: 10 },
  drone: { key: 'drone', name: 'Drone', cd: 30, dur: 18 },
  decoy: { key: 'decoy', name: 'Decoy', cd: 22, dur: 6 },
  emp: { key: 'emp', name: 'EMP', cd: 16, radius: 240 },
};

const ENEMY_TYPES = {
  skitterling: {
    name: 'Skitterling',
    hp: 35,
    speed: 120,
    damage: 8,
    attackCd: 0.8,
    radius: 11,
    range: 22,
    color: '#ff5d4d',
    score: 4,
    kind: 'melee',
  },
  sporeMantis: {
    name: 'Spore Mantis',
    hp: 90,
    speed: 75,
    damage: 14,
    attackCd: 1.5,
    radius: 14,
    range: 260,
    color: '#c06bff',
    score: 9,
    kind: 'ranged',
  },
  carapaceBull: {
    name: 'Carapace Bull',
    hp: 280,
    speed: 65,
    damage: 28,
    attackCd: 1.4,
    radius: 22,
    range: 30,
    color: '#ff9a3d',
    score: 18,
    kind: 'charger',
    armor: 0.35,
  },
  broodWarden: {
    name: 'Brood Warden',
    hp: 380,
    speed: 50,
    damage: 18,
    attackCd: 1.2,
    radius: 25,
    range: 34,
    color: '#b02040',
    score: 28,
    kind: 'warden',
  },
};

const UPGRADES = {
  cloneHealth: {
    name: 'Reinforced Clone Tissue',
    desc: '+20 max clone health',
    credits: 120,
    res: { bioResin: 10 },
    max: 5,
  },
  rifleDamage: {
    name: 'Rifle Capacitor',
    desc: '+15% Pulse Rifle damage',
    credits: 150,
    res: { softQuartz: 8 },
    max: 5,
  },
  cargoHarness: {
    name: 'Cargo Harness',
    desc: '+2 carry weight',
    credits: 100,
    res: { salvageChips: 10 },
    max: 5,
  },
  muleArmor: {
    name: 'Mule Armor',
    desc: '+100 HP for the Mule-3 hauler',
    credits: 160,
    res: { salvageChips: 15 },
    max: 5,
  },
  deviceCooling: {
    name: 'Device Cooling',
    desc: '-15% device cooldown',
    credits: 140,
    res: { sporeFiber: 8 },
    max: 4,
  },
  marketContacts: {
    name: 'Market Contacts',
    desc: '+10% resource sell price',
    credits: 200,
    res: {},
    max: 4,
  },
  signalArray: {
    name: 'Signal Array',
    desc: 'Signal Stability drops 25% slower',
    credits: 130,
    res: { softQuartz: 6 },
    max: 3,
  },
  hydroponicsTray: {
    name: 'Hydroponics Tray',
    desc: '+3 Bio Resin after each mission',
    credits: 180,
    res: { bioResin: 12 },
    max: 3,
  },
};

const MISSIONS = {
  resourceRun: {
    key: 'resourceRun',
    name: 'Resource Run',
    brief: 'Deliver 120 cr of resources to the Cargo Pad.',
    bonusBrief: 'Bonus: deliver 200+ cr.',
  },
  hivePurge: {
    key: 'hivePurge',
    name: 'Hive Purge',
    brief: 'Destroy 2 hives.',
    bonusBrief: 'Bonus: destroy a level 3 hive.',
  },
  outpostRecovery: {
    key: 'outpostRecovery',
    name: 'Outpost Recovery',
    brief: 'Activate the reactor, deliver 60 cr and hold for 90s.',
    bonusBrief: 'Bonus: Mule-3 must survive.',
  },
  apexHunt: {
    key: 'apexHunt',
    name: 'Apex Hunt',
    brief: 'Lure out and slay the Apex Warden.',
    bonusBrief: 'Bonus: kill it within 90s of its arrival.',
  },
};

const HAZARDS = {
  sporeCloud: {
    name: 'Spore Cloud',
    radius: 95,
    color: 'rgba(176,107,255,0.16)',
    edge: 'rgba(176,107,255,0.4)',
    status: 'corrode',
  },
  acidPool: {
    name: 'Acid Pool',
    radius: 70,
    color: 'rgba(157,255,93,0.14)',
    edge: 'rgba(157,255,93,0.45)',
    status: 'burn',
  },
  emberVent: {
    name: 'Ember Vent',
    radius: 55,
    color: 'rgba(255,154,61,0.15)',
    edge: 'rgba(255,154,61,0.5)',
    interval: 2.5,
    damage: 16,
  },
};

const BIOMES = [
  {
    key: 'fen',
    name: 'Morrow Fen',
    bgTop: '#0a1410',
    bgBottom: '#08100e',
    deco: { puddle: 'rgba(40,180,140,', plant: 'rgba(110,230,170,', tip: 'rgba(150,255,200,' },
    hazardBias: { sporeCloud: 2, acidPool: 1, emberVent: 0.5 },
  },
  {
    key: 'ashen',
    name: 'Ashen Reach',
    bgTop: '#120c08',
    bgBottom: '#0d0906',
    deco: { puddle: 'rgba(200,120,40,', plant: 'rgba(230,150,90,', tip: 'rgba(255,200,150,' },
    hazardBias: { sporeCloud: 0.5, acidPool: 0.5, emberVent: 2.5 },
  },
  {
    key: 'mire',
    name: 'Violet Mire',
    bgTop: '#0c0814',
    bgBottom: '#08060e',
    deco: { puddle: 'rgba(140,80,200,', plant: 'rgba(180,120,255,', tip: 'rgba(220,180,255,' },
    hazardBias: { sporeCloud: 2.5, acidPool: 1.5, emberVent: 0.3 },
  },
];

const STATUS = {
  burn: { dps: 9, dur: 3, tick: 0.5, color: '#ff9a3d' },
  freeze: { slow: 0.45, dur: 2.2, color: '#9adfff' },
  corrode: { armorShred: 0.6, dur: 4, color: '#b6ff5d' },
  stun: { slow: 0.05, dur: 1.4, color: '#7af5ff' },
};

export {
  WORLD_W,
  WORLD_H,
  RESOURCE_TYPES,
  WEAPONS,
  ENEMY_TYPES,
  UPGRADES,
  MISSIONS,
  STATUS,
  DEVICES,
  HAZARDS,
  BIOMES,
};
